# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/controller.schema.json

controllers:
  resource:
    path: ../../src/Controller/
    namespace: App\Controller
  type: attribute

